FROM denoland/deno:2.6.4
ARG VERSION
# ENV DENO_DEPLOYMENT_ID=${VERSION}
ENV PORT=5418

WORKDIR /app

COPY . .
RUN deno cache main.ts

EXPOSE 5418

CMD ["run", "--config", "./deno.jsonc", "-A", "--unstable-detect-cjs", "main.ts"]
